// app/lib/series-data.js

const SeriesData = [
  {
    id: "01",
    name: "18 Again",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "02",
    name: "3 Body Problem",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "03",
    name: "9-1-1 Lone Star",
    totalSeasons: 3,
    upcomingSeasons: ["S 04"],
    watchedSeasons: [true, true, false],
    watchProgress: 67,
  },
  {
    id: "04",
    name: "9-1-1",
    totalSeasons: 3,
    upcomingSeasons: ["S 04"],
    watchedSeasons: [true, true, false],
    watchProgress: 67,
  },
  {
    id: "05",
    name: "Avatar The Last Airbender",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "06",
    name: "Banshee",
    totalSeasons: 5,
    upcomingSeasons: ["S 06"],
    watchedSeasons: [true, true, true, false, false],
    watchProgress: 60,
  },
  {
    id: "07",
    name: "Berlin",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "08",
    name: "Bodies",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "09",
    name: "Echo",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "10",
    name: "Fallout",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "11",
    name: "Fargo",
    totalSeasons: 1,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "12",
    name: "Gen V",
    totalSeasons: 1,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "13",
    name: "HALO",
    totalSeasons: 3,
    upcomingSeasons: ["S 04"],
    watchedSeasons: [true, false, false],
    watchProgress: 33,
  },
  {
    id: "14",
    name: "La Brea",
    totalSeasons: 4,
    upcomingSeasons: ["S 05"],
    watchedSeasons: [true, true, true, false],
    watchProgress: 75,
  },
  {
    id: "15",
    name: "Loki",
    totalSeasons: 3,
    upcomingSeasons: ["S 04"],
    watchedSeasons: [true, true, false],
    watchProgress: 67,
  },
  {
    id: "16",
    name: "Lupin",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "17",
    name: "Manifest",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "18",
    name: "Monarch Legacy of Monsters",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "19",
    name: "Mr and Mrs Smith",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "20",
    name: "Mr. Robot",
    totalSeasons: 5,
    upcomingSeasons: ["S 06"],
    watchedSeasons: [true, true, true, true, false],
    watchProgress: 80,
  },
  {
    id: "21",
    name: "One Piece",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "22",
    name: "Panchayat",
    totalSeasons: 4,
    upcomingSeasons: ["S 05"],
    watchedSeasons: [true, true, true, false],
    watchProgress: 75,
  },
  {
    id: "23",
    name: "Percy Jackson and the Olympians",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "24",
    name: "Reacher",
    totalSeasons: 3,
    upcomingSeasons: ["S 04"],
    watchedSeasons: [true, true, false],
    watchProgress: 67,
  },
  {
    id: "25",
    name: "Resident Alien",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "26",
    name: "Secret Invasion Season",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "27",
    name: "Sex Education",
    totalSeasons: 5,
    upcomingSeasons: ["S 06"],
    watchedSeasons: [true, true, true, true, false],
    watchProgress: 80,
  },
  {
    id: "28",
    name: "Sherlock Holmes",
    totalSeasons: 4,
    upcomingSeasons: ["S 05"],
    watchedSeasons: [true, true, true, false],
    watchProgress: 75,
  },
  {
    id: "29",
    name: "Silo Season",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "30",
    name: "Stan Lees Lucky Man",
    totalSeasons: 4,
    upcomingSeasons: ["S 05"],
    watchedSeasons: [true, true, true, false],
    watchProgress: 75,
  },
  {
    id: "31",
    name: "Sweet Tooth",
    totalSeasons: 3,
    upcomingSeasons: ["S 04"],
    watchedSeasons: [true, true, false],
    watchProgress: 67,
  },
  {
    id: "32",
    name: "Tehran",
    totalSeasons: 3,
    upcomingSeasons: ["S 04"],
    watchedSeasons: [true, true, false],
    watchProgress: 67,
  },
  {
    id: "33",
    name: "The Bear",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "34",
    name: "The Good Doctor",
    totalSeasons: 7,
    upcomingSeasons: ["S 08"],
    watchedSeasons: [true, true, true, true, true, true, false],
    watchProgress: 86,
  },
  {
    id: "35",
    name: "The Night Agent",
    totalSeasons: 2,
    upcomingSeasons: ["S 03"],
    watchedSeasons: [true, false],
    watchProgress: 50,
  },
  {
    id: "36",
    name: "The Umbrella Academy",
    totalSeasons: 4,
    upcomingSeasons: ["S 05"],
    watchedSeasons: [true, true, true, false],
    watchProgress: 75,
  },
  {
    id: "37",
    name: "The Walking Dead",
    totalSeasons: 11,
    upcomingSeasons: ["S 12"],
    watchedSeasons: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    watchProgress: 91,
  },
  {
    id: "38",
    name: "Tom Clancys Jack Ryan",
    totalSeasons: 5,
    upcomingSeasons: ["S 06"],
    watchedSeasons: [true, true, true, true, false],
    watchProgress: 80,
  },
  {
    id: "39",
    name: "Under the Dome",
    totalSeasons: 4,
    upcomingSeasons: ["S 05"],
    watchedSeasons: [true, true, true, false],
    watchProgress: 75,
  },
  {
    id: "40",
    name: "Young Sheldon",
    totalSeasons: 7,
    upcomingSeasons: ["S 08"],
    watchedSeasons: [true, true, true, true, true, true, false],
    watchProgress: 86,
  },
  {
    id: "41",
    name: "Brooklyn Nine Nine",
    totalSeasons: 9,
    upcomingSeasons: ["S 10"],
    watchedSeasons: [true, true, true, true, true, false, false, false, false],
    watchProgress: 56,
  },
  {
    id: "42",
    name: "Better Call Saul",
    totalSeasons: 7,
    upcomingSeasons: ["S 08"],
    watchedSeasons: [true, true, true, true, true, true, false],
    watchProgress: 86,
  },
  {
    id: "43",
    name: "Breaking Bad",
    totalSeasons: 6,
    upcomingSeasons: ["Series Ended"],
    watchedSeasons: [true, true, true, true, true, true],
    watchProgress: 0,
  },
  // Add more series add the same structure
];

export default SeriesData;
